version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: doc1_database
    ports:
      - 5433:5432 # Maps external port 5433 to internal port 5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=doc-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  backend:
    build:
      context: ./Spring
    image: backend/assignment
    container_name: doc1_backend
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/doc-db?currentSchema=doc1
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  frontend:
    build:
      context: ./React
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: http://localhost:8080
    image: frontend/assignment
    container_name: doc1_frontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    depends_on:
      - backend

volumes:
  db:
    driver: local
